name: 'Firebase App Distribution'
description: 'GitHub Action that uploads artifacts to Firebase App Distribution, via safe opinionated project structure'
author: 'Esteban Chacon <@etherbeing>'
inputs:
  appId:
    description: 'App id can be found on the General Settings page'
    required: true
  gpgSecretsKey:
    required: true
    description: "DO NOT UPLOAD CREDENTIALS INSTEAD USE A SAFE GIT SECRET KEY FOR REVEALING THEM, you may rotate it if you want to..."
  googleAppCreds:
    required: false
    default: "service-credentials.json"
    description: "Defaults to "

branding:
  color: 'green'
  icon: 'send'

runs:
  using: 'composite'
  steps:
    - name:  
      shell: bash
      env: 
        - GPG_TTY: /dev/tty
        - GOOGLE_APPLICATION_CREDENTIALS: ${{inputs.googleAppCreds}}
      run: |
        apt-get update && apt-get install -y git-secret gnupg curl bash
        curl -sL https://firebase.tools | bash
        echo "${{ inputs.gpgSecretsKey }}" | gpg --batch --import
        git secret reveal
        firebase appdistribution:distribute ${{inputs.file:-./build/app/outputs/flutter-apk/app-debug.apk}} --app ${{inputs.appId}}
