name: 'Firebase App Distribution'
description: 'GitHub Action that uploads artifacts to Firebase App Distribution, via safe opinionated project structure'
author: 'Esteban Chacon <@etherbeing>'
inputs:
  appId:
    description: 'App id can be found on the General Settings page'
    required: true
  gpgSecretsKey:
    required: true
    description: "DO NOT UPLOAD CREDENTIALS INSTEAD USE A SAFE GIT SECRET KEY FOR REVEALING THEM, you may rotate it if you want to..."
  googleAppCreds:
    required: false
    default: "service-credentials.json"
    description: "The service credentials json key..."
  file:
    required: false
    default: ./build/app/outputs/flutter-apk/app-debug.apk
    description: "Where the APK goes to"
  withSudoAccess:
    required: false
    default: "false"
    description: "Use only to prepare a host to run this, useful for when running on non self-hosted containers"
  groups:
    required: false
    description: "A comma separated list of tester's groups to include in this release"
  releaseNotesFiles:
    required: false
    default: CHANGELOG.md
    description: "File pointing to the release notes"
branding:
  color: 'green'
  icon: 'send'

runs:
  using: 'composite'
  steps:
    - name: Prepare System (Optional)
      if: ${{ inputs.withSudoAccess == 'true' }}
      shell: bash
      run: |
        set -e

        if ! command -v sudo >/dev/null 2>&1; then
          echo "sudo not available; cannot install system dependencies"
          exit 1
        fi

        sudo apt-get update
        sudo apt-get install -y gnupg curl git-secret

        if ! command -v firebase >/dev/null 2>&1; then
          curl -sL https://firebase.tools | sudo bash
        fi
    - name: Import key, reveal secrets and distribute app
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.googleAppCreds }}
      run: |
        firebase appdistribution:distribute ${{ inputs.file }} --app ${{ inputs.appId }} --groups ${{ inputs.groups }} --release-notes-file ${{ inputs.releaseNotesFiles }}
